-- Organization の Settings 直下のサブチャプター（Repository / Codespaces / Planning / Copilot）と、
-- Copilot 配下の Access / Policies / Models / Custom instructions / Content exclusion / Cloud agent、
-- Planning 配下の Projects / Issue Types、Codespaces 配下の General / Policies、
-- Repository 配下の General / Topics / Rulesets / Rule insights / Bypass requests / Custom properties。
-- さらに Organization Settings 直下に Actions / Models / Webhooks / Discussions / Packages /
-- Pages / Hosted compute networking / Custom properties を追加。
-- さらに Authentication security / Advanced Security / Deploy keys / Compliance /
-- Vertified and approved domains / Secrets and variables / GitHub Apps /
-- OAuth app policy / Personal access tokens を追加。
-- さらに Advanced Security 配下の Configurations / Global settings を追加。
-- さらに Personal access tokens 配下の settings / Active tokens / Prnding requests を追加。
-- 実行: Supabase MCP execute_sql またはサービスロールで実行。
-- 再実行時は ON CONFLICT で更新されます。

INSERT INTO programming_chapters (
  id, language_id, parent_id, title, description, "order", status, exercises,
  video_url, thumbnail_url, duration, created_at, updated_at
) VALUES
  ('github-enterprise-org-settings-repository', 'github', 'github-enterprise-org-settings', 'Repository',
   'Organization Settings の Repository。リポジトリ作成・可視性・フォーク・デフォルトブランチなど組織横断のリポジトリポリシーを学びます。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-codespaces', 'github', 'github-enterprise-org-settings', 'Codespaces',
   'Organization Settings の Codespaces。利用者範囲・シークレット・既定環境など組織レベルの Codespaces 方針を学びます。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-planning', 'github', 'github-enterprise-org-settings', 'Planning',
   'Organization Settings の Planning。Issues・Projects など計画系機能に関する組織既定の考え方を学びます。',
   3, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot', 'github', 'github-enterprise-org-settings', 'Copilot',
   'Organization Settings の Copilot 入口。Access / Policies / Models など各サブ項目は子チャプターで学びます。',
   4, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-access', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Access',
   'Organization の Copilot で誰にライセンスを割り当てるか、利用の入口を学びます。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-policies', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Policies',
   'Chat・PR・CLI など Copilot 機能別の Organization ポリシーを学びます。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-models', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Models',
   '利用可能モデルと既定モデルを Organization で揃える考え方を学びます。',
   3, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-custom-instructions', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Custom instructions',
   '組織共通のカスタム指示で Copilot の振る舞いを揃える方法を学びます。',
   4, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-content-exclusion', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Content exclusion',
   'コンテンツ除外で機密コードの扱いリスクを下げる設定を学びます。',
   5, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-copilot-cloud-agent', 'github', 'github-enterprise-org-settings-copilot', 'Copilot — Cloud agent',
   'クラウドエージェントの利用と Organization / Enterprise ポリシーとの関係を学びます。',
   6, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-planning-projects', 'github', 'github-enterprise-org-settings-planning', 'Projects',
   'Organization Settings › Planning における Projects。組織レベルのプロジェクト方針と Organization 横断の運用の考え方を学びます。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-planning-issue-types', 'github', 'github-enterprise-org-settings-planning', 'Issue Types',
   'Organization Settings › Planning › Issue types。組織共通の issue の種類の作成・編集・無効化を学びます。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-codespaces-general', 'github', 'github-enterprise-org-settings-codespaces', 'General',
   'Organization Settings › Codespaces › General。利用対象、既定設定、開発環境の土台を整理します。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-codespaces-policies', 'github', 'github-enterprise-org-settings-codespaces', 'Policies',
   'Organization Settings › Codespaces › Policies。アクセス範囲やセキュリティ制御などの利用ポリシーを整理します。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-general', 'github', 'github-enterprise-org-settings-repository', 'General',
   'Organization Settings › Repository › General。リポジトリの基本設定・既定値を整理します。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-topics', 'github', 'github-enterprise-org-settings-repository', 'Topics',
   'Organization Settings › Repository › Topics。分類タグ運用を整理します。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-rulesets', 'github', 'github-enterprise-org-settings-repository', 'Rulesets',
   'Organization Settings › Repository › Rulesets。リポジトリルールの標準化を整理します。',
   3, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-rule-insights', 'github', 'github-enterprise-org-settings-repository', 'Rule insights',
   'Organization Settings › Repository › Rule insights。ルール適用状況の分析を整理します。',
   4, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-bypass-requests', 'github', 'github-enterprise-org-settings-repository', 'Bypass requests',
   'Organization Settings › Repository › Bypass requests。例外申請フローを整理します。',
   5, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-repository-custom-properties', 'github', 'github-enterprise-org-settings-repository', 'Custom properties',
   'Organization Settings › Repository › Custom properties。メタデータ管理と自動化の基盤を整理します。',
   6, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-actions', 'github', 'github-enterprise-org-settings', 'Actions',
   'Organization Settings の Actions。ワークフロー実行方針と利用制御を学びます。',
   5, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-models', 'github', 'github-enterprise-org-settings', 'Models',
   'Organization Settings の Models。利用可能モデルと統制を学びます。',
   6, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-webhooks', 'github', 'github-enterprise-org-settings', 'Webhooks',
   'Organization Settings の Webhooks。組織全体イベント連携を学びます。',
   7, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-discussions', 'github', 'github-enterprise-org-settings', 'Discussions',
   'Organization Settings の Discussions。コミュニティ運用と統制を学びます。',
   8, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-packages', 'github', 'github-enterprise-org-settings', 'Packages',
   'Organization Settings の Packages。パッケージ公開とアクセス方針を学びます。',
   9, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-pages', 'github', 'github-enterprise-org-settings', 'Pages',
   'Organization Settings の Pages。公開サイト運用方針を学びます。',
   10, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-hosted-compute-networking', 'github', 'github-enterprise-org-settings', 'Hosted compute networking',
   'Organization Settings の Hosted compute networking。ネットワーク連携と制御を学びます。',
   11, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-custom-properties', 'github', 'github-enterprise-org-settings', 'Custom properties',
   'Organization Settings の Custom properties。組織共通メタデータ管理を学びます。',
   12, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-authentication-security', 'github', 'github-enterprise-org-settings', 'Authentication security',
   'Organization Settings の Authentication security。認証とアクセス保護の基盤を学びます。',
   13, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-advanced-security', 'github', 'github-enterprise-org-settings', 'Advanced Security',
   'Organization Settings の Advanced Security。GHAS 系の統制を学びます。',
   14, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-deploy-keys', 'github', 'github-enterprise-org-settings', 'Deploy keys',
   'Organization Settings の Deploy keys。鍵管理ポリシーを学びます。',
   15, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-compliance', 'github', 'github-enterprise-org-settings', 'Compliance',
   'Organization Settings の Compliance。監査・規制要件対応を学びます。',
   16, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-vertified-approved-domains', 'github', 'github-enterprise-org-settings', 'Vertified and approved domains',
   'Organization Settings の Vertified and approved domains。承認済みドメイン運用を学びます。',
   17, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-secrets-and-variables', 'github', 'github-enterprise-org-settings', 'Secrets and variables',
   'Organization Settings の Secrets and variables。シークレット統制を学びます。',
   18, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-github-apps', 'github', 'github-enterprise-org-settings', 'GitHub Apps',
   'Organization Settings の GitHub Apps。アプリ権限と承認運用を学びます。',
   19, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-oauth-app-policy', 'github', 'github-enterprise-org-settings', 'OAuth app policy',
   'Organization Settings の OAuth app policy。OAuth 連携統制を学びます。',
   20, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-personal-access-tokens', 'github', 'github-enterprise-org-settings', 'Personal access tokens',
   'Organization Settings の Personal access tokens。PAT 制御を学びます。',
   21, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-scheduled-reminders', 'github', 'github-enterprise-org-settings', 'Scheduled reminders',
   'Organization Settings の Scheduled reminders。定期通知の運用を学びます。',
   22, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-announcement', 'github', 'github-enterprise-org-settings', 'Announcement',
   'Organization Settings の Announcement。組織向けアナウンス運用を学びます。',
   23, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-logs', 'github', 'github-enterprise-org-settings', 'Logs',
   'Organization Settings の Logs。監査ログ・運用ログ確認を学びます。',
   24, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-deleted-repositories', 'github', 'github-enterprise-org-settings', 'Deleted repositories',
   'Organization Settings の Deleted repositories。削除済みリポジトリ管理を学びます。',
   25, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-developer-settings', 'github', 'github-enterprise-org-settings', 'Developer settings',
   'Organization Settings の Developer settings。開発者向け設定運用を学びます。',
   26, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-logs-sponsorship-log', 'github', 'github-enterprise-org-settings-logs', 'Sponsorship log',
   'Organization Settings › Logs › Sponsorship log。スポンサー関連のログ確認を学びます。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-logs-audit-log', 'github', 'github-enterprise-org-settings-logs', 'Audit log',
   'Organization Settings › Logs › Audit log。監査ログの確認を学びます。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-advanced-security-configurations', 'github', 'github-enterprise-org-settings-advanced-security', 'Configurations',
   'Organization Settings › Advanced Security › Configurations。セキュリティ構成の定義・適用と保護率を整理します。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-advanced-security-global-settings', 'github', 'github-enterprise-org-settings-advanced-security', 'Global settings',
   'Organization Settings › Advanced Security › Global settings。組織全体の既定設定を整理します。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-personal-access-tokens-settings', 'github', 'github-enterprise-org-settings-personal-access-tokens', 'settings',
   'Organization Settings › Personal access tokens › settings。Fine-grained token の許可・承認・有効期限ポリシーを学びます。',
   1, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-personal-access-tokens-active-tokens', 'github', 'github-enterprise-org-settings-personal-access-tokens', 'Active tokens',
   'Organization Settings › Personal access tokens › Active tokens。発行済み token の棚卸しを学びます。',
   2, 'published', '[]'::jsonb, '', '', '', NOW(), NOW()),
  ('github-enterprise-org-settings-personal-access-tokens-prnding-requests', 'github', 'github-enterprise-org-settings-personal-access-tokens', 'Prnding requests',
   'Organization Settings › Personal access tokens › Prnding requests。承認待ちリクエスト審査を学びます。',
   3, 'published', '[]'::jsonb, '', '', '', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  parent_id = EXCLUDED.parent_id,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  "order" = EXCLUDED."order",
  status = EXCLUDED.status,
  exercises = EXCLUDED.exercises,
  updated_at = NOW();
